import { RoutingProtocol } from "@/shared/types/common/protocols";
import type { UUID } from "@/shared/types/common/uuid";

export enum StepType {
  Move = "MOVE",
  Message = "MESSAGE",
  Toggle = "TOGGLE_STATUS",
  Refresh = "REFRESH",
}

export enum RefreshAction {
  BatmanElp = "BATMAN_ELP",
  BatmanOgm = "BATMAN_OGM",
  DsdvFullDump = "DSDV_FULL_DUMP",
  DsdvIncremental = "DSDV_INCREMENTAL",
  AodvHello = "AODV_HELLO",
  OlsrHello = "OLSR_HELLO",
  OlsrTc = "OLSR_TC",
}

export interface BaseStep {
  id: UUID;
  title: string;
  tick: number;
}

export interface MessageStep extends BaseStep {
  type: StepType.Message;
  sourcePeerId: UUID | null;
  destinationPeerId: UUID | null;
}

export interface MoveStep extends BaseStep {
  type: StepType.Move;
  movePeerId: UUID | null;
  x: number;
  y: number;
}

export interface ToggleStep extends BaseStep {
  type: StepType.Toggle;
  targetEntityId: UUID | null;
}

export interface RefreshStep extends BaseStep {
  type: StepType.Refresh;
  refreshPeerId: UUID;
  refreshProtocol: RoutingProtocol;
  refreshAction?: RefreshAction;
  refreshStartTick: number;
  refreshInterval: number;
  autoGenerated: true;
}

export type ManualWorkflowStep = MessageStep | MoveStep | ToggleStep;

export type WorkflowStep = ManualWorkflowStep | RefreshStep;

export const isMessageStep = (step: WorkflowStep): step is MessageStep => {
  return step.type === StepType.Message;
};

export const isMoveStep = (step: WorkflowStep): step is MoveStep => {
  return step.type === StepType.Move;
};

export const isToggleStep = (step: WorkflowStep): step is ToggleStep => {
  return step.type === StepType.Toggle;
};

export const isRefreshStepType = (step: WorkflowStep): step is RefreshStep => {
  return step.type === StepType.Refresh;
};

export const createStepBase = (base: BaseStep) => {
  return {
    id: base.id,
    title: base.title,
    tick: Math.max(1, Math.floor(base.tick || 1)),
  } satisfies BaseStep;
};

export type WorkflowStepType = WorkflowStep["type"];
