import { peerRoutingProtocols, workflowStepTypes } from "@/shared/constants/protocol";
import { EntityType } from "@/shared/types/model/entities";
import type { NetworkEntity } from "@/shared/types/model/entities";
import { RoutingProtocol } from "@/shared/types/common/protocols";
import { RefreshAction, StepType, type WorkflowStep } from "@/shared/types/model/steps";

export type WorkspaceImportPayload = {
  entities: NetworkEntity[];
  steps: WorkflowStep[];
};

const isRecord = (value: unknown): value is Record<string, unknown> => {
  return typeof value === "object" && value !== null;
};

const isFiniteNumber = (value: unknown): value is number => {
  return typeof value === "number" && Number.isFinite(value);
};

const isNullableString = (value: unknown): value is string | null => {
  return typeof value === "string" || value === null;
};

const isValidProtocol = (value: unknown): value is RoutingProtocol => {
  return typeof value === "string" && peerRoutingProtocols.includes(value as RoutingProtocol);
};

const isValidConfiguration = (protocol: RoutingProtocol, value: unknown) => {
  if (!isRecord(value)) {
    return false;
  }

  switch (protocol) {
    case RoutingProtocol.BATMAN:
      return (
        isFiniteNumber(value.distancePenaltyDistance) &&
        value.distancePenaltyDistance > 0 &&
        isFiniteNumber(value.distancePenaltyPercent) &&
        value.distancePenaltyPercent >= 0 &&
        isFiniteNumber(value.elpInterval) &&
        value.elpInterval > 0 &&
        isFiniteNumber(value.ogmInterval) &&
        value.ogmInterval > 0 &&
        isFiniteNumber(value.purgeTimeout) &&
        value.purgeTimeout > 0
      );
    case RoutingProtocol.DSDV:
      return (
        isFiniteNumber(value.incrementalUpdateInterval) &&
        value.incrementalUpdateInterval > 0 &&
        isFiniteNumber(value.fullDumpInterval) &&
        value.fullDumpInterval > 0 &&
        isFiniteNumber(value.routeTimeout) &&
        value.routeTimeout > 0
      );
    case RoutingProtocol.AODV:
      return (
        isFiniteNumber(value.helloInterval) &&
        value.helloInterval > 0 &&
        isFiniteNumber(value.routeTimeout) &&
        value.routeTimeout > 0
      );
    case RoutingProtocol.OLSR:
      return (
        isFiniteNumber(value.helloInterval) &&
        value.helloInterval > 0 &&
        isFiniteNumber(value.tcInterval) &&
        value.tcInterval > 0
      );
    case RoutingProtocol.DSR:
      return true;
  }
};

const isValidNetworkEntity = (value: unknown): value is NetworkEntity => {
  if (!isRecord(value) || typeof value.id !== "string" || typeof value.name !== "string") {
    return false;
  }

  if ("locked" in value && typeof value.locked !== "boolean") {
    return false;
  }

  if (value.type === EntityType.Peer) {
    return (
      isFiniteNumber(value.x) &&
      isFiniteNumber(value.y) &&
      isFiniteNumber(value.range) &&
      value.range > 0 &&
      typeof value.enabled === "boolean" &&
      isValidProtocol(value.protocol) &&
      isValidConfiguration(value.protocol, value.configuration)
    );
  }

  if (value.type === EntityType.Link) {
    return (
      isNullableString(value.sourcePeerId) &&
      isNullableString(value.destinationPeerId) &&
      typeof value.enabled === "boolean"
    );
  }

  if (value.type === EntityType.Obstacle) {
    return (
      isFiniteNumber(value.x) &&
      isFiniteNumber(value.y) &&
      isFiniteNumber(value.width) &&
      value.width > 0 &&
      isFiniteNumber(value.height) &&
      value.height > 0
    );
  }

  return false;
};

const isValidWorkflowStep = (value: unknown): value is WorkflowStep => {
  if (!isRecord(value)) {
    return false;
  }

  if (
    typeof value.id !== "string" ||
    typeof value.title !== "string" ||
    !workflowStepTypes.includes(value.type as WorkflowStep["type"]) ||
    !isFiniteNumber(value.tick)
  ) {
    return false;
  }

  if (value.type === StepType.Message) {
    return isNullableString(value.sourcePeerId) && isNullableString(value.destinationPeerId);
  }

  if (value.type === StepType.Move) {
    return isNullableString(value.movePeerId) && isFiniteNumber(value.x) && isFiniteNumber(value.y);
  }

  if (value.type === StepType.Toggle) {
    return isNullableString(value.targetEntityId);
  }

  if (value.type === StepType.Refresh) {
    return (
      isNullableString(value.refreshPeerId) &&
      (value.refreshProtocol == null ||
        peerRoutingProtocols.includes(value.refreshProtocol as RoutingProtocol)) &&
      (value.refreshAction == null ||
        Object.values(RefreshAction).includes(value.refreshAction as RefreshAction)) &&
      (value.refreshStartTick == null || isFiniteNumber(value.refreshStartTick)) &&
      (value.refreshInterval == null || isFiniteNumber(value.refreshInterval)) &&
      (value.autoGenerated == null || typeof value.autoGenerated === "boolean")
    );
  }

  return false;
};

export const parseWorkspaceImportPayload = (raw: string): WorkspaceImportPayload => {
  let parsed: unknown;

  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Invalid JSON file.");
  }

  if (!isRecord(parsed)) {
    throw new Error("File must contain a JSON object.");
  }

  if (!Array.isArray(parsed.entities) || !parsed.entities.every(isValidNetworkEntity)) {
    throw new Error("Invalid entities list in file.");
  }

  if (!Array.isArray(parsed.steps) || !parsed.steps.every(isValidWorkflowStep)) {
    throw new Error("Invalid steps list in file.");
  }

  return {
    entities: parsed.entities,
    steps: parsed.steps,
  };
};

export const getWorkspaceExportFileName = (date = new Date()) => {
  const toPart = (value: number) => String(value).padStart(2, "0");
  const stamp = `${date.getFullYear()}${toPart(date.getMonth() + 1)}${toPart(date.getDate())}-${toPart(
    date.getHours(),
  )}${toPart(date.getMinutes())}${toPart(date.getSeconds())}`;
  return `mesh-io-export-${stamp}.json`;
};
