import { StepType } from "../enums";
import type { PeerRoutingProtocol } from "../navigation";

export type WorkflowStep = {
  id: string;
  title: string;
  type: StepType;
  tick: number;
  sourcePeerId: string | null;
  destinationPeerId: string | null;
  targetEntityId: string | null;
  movePeerId: string | null;
  x: number;
  y: number;
  refreshPeerId?: string | null;
  refreshProtocol?: PeerRoutingProtocol | null;
  refreshStartTick?: number | null;
  refreshInterval?: number | null;
  autoGenerated?: boolean;
};
