import { StepType } from "../enums";
import type { PeerRoutingProtocol } from "../navigation";

export type BaseWorkflowStep = {
  id: string;
  title: string;
  tick: number;
};

export type MessageStep = BaseWorkflowStep & {
  type: typeof StepType.Message;
  sourcePeerId: string;
  destinationPeerId: string;
};

export type MoveStep = BaseWorkflowStep & {
  type: typeof StepType.Move;
  movePeerId: string;
  x: number;
  y: number;
};

export type ToggleStatusStep = BaseWorkflowStep & {
  type: typeof StepType.ToggleStatus;
  targetEntityId: string;
};

export type RefreshStep = BaseWorkflowStep & {
  type: typeof StepType.Refresh;
  refreshPeerId: string;
  refreshProtocol: PeerRoutingProtocol;
  refreshStartTick: number;
  refreshInterval: number;
  autoGenerated: true;
};

export type ManualWorkflowStep = MessageStep | MoveStep | ToggleStatusStep;

export type WorkflowStep = ManualWorkflowStep | RefreshStep;

export const isMessageStep = (step: WorkflowStep): step is MessageStep => {
  return step.type === StepType.Message;
};

export const isMoveStep = (step: WorkflowStep): step is MoveStep => {
  return step.type === StepType.Move;
};

export const isToggleStatusStep = (step: WorkflowStep): step is ToggleStatusStep => {
  return step.type === StepType.ToggleStatus;
};

export const isRefreshStepType = (step: WorkflowStep): step is RefreshStep => {
  return step.type === StepType.Refresh;
};

export const createStepBase = (base: BaseWorkflowStep) => {
  return {
    id: base.id,
    title: base.title,
    tick: Math.max(1, Math.floor(base.tick || 1)),
  } satisfies BaseWorkflowStep;
};

export type WorkflowStepType = WorkflowStep["type"];
