import { useEffect, useMemo, useState } from "react";

import Navigation from "../../components/Navigation/Navigation";
import Properties from "../../components/Properties/Properties";
import Toolbar from "../../components/Toolbar/Toolbar";
import Workspace from "../../components/Workspace/Workspace";
import { useLocalStorage } from "../../hooks/storage/useLocalStorage";
import { useToast } from "../../hooks/useToast";
import type { NetworkEntity } from "../../types/navigation";
import type { PeerRoutingProtocol } from "../../types/navigation";
import type { WorkflowStep } from "../../types/steps";
import { INITIAL_NETWORK_ENTITIES } from "../../utils/navigation/entities";
import { composeStepsWithRefresh, sanitizeManualSteps } from "../../utils/navigation/refreshSteps";
import { INITIAL_WORKFLOW_STEPS } from "../../utils/navigation/steps";

type ImportPayload = {
  entities: NetworkEntity[];
  steps: WorkflowStep[];
};

const ALLOWED_STEP_TYPES: WorkflowStep["type"][] = ["MOVE", "MESSAGE", "TOGGLE", "REFRESH"];
const ALLOWED_PROTOCOLS: PeerRoutingProtocol[] = ["HWMP", "BATMAN", "OLSR", "AODV", "DSR"];

const isRecord = (value: unknown): value is Record<string, unknown> => {
  return typeof value === "object" && value !== null;
};

const isFiniteNumber = (value: unknown): value is number => {
  return typeof value === "number" && Number.isFinite(value);
};

const isNullableString = (value: unknown): value is string | null => {
  return typeof value === "string" || value === null;
};

const isValidProtocolList = (value: unknown): value is PeerRoutingProtocol[] => {
  return (
    Array.isArray(value) &&
    value.every((item) => ALLOWED_PROTOCOLS.includes(item as PeerRoutingProtocol))
  );
};

const isValidNetworkEntity = (value: unknown): value is NetworkEntity => {
  if (!isRecord(value) || typeof value.id !== "string" || typeof value.name !== "string") {
    return false;
  }

  if ("locked" in value && typeof value.locked !== "boolean") {
    return false;
  }

  if (value.type === "PEER") {
    return (
      isFiniteNumber(value.x) &&
      isFiniteNumber(value.y) &&
      isFiniteNumber(value.range) &&
      typeof value.enabled === "boolean" &&
      isValidProtocolList(value.protocols) &&
      isFiniteNumber(value.batmanOgmInterval) &&
      isFiniteNumber(value.batmanPurgeTimeout)
    );
  }

  if (value.type === "LINK") {
    return (
      isNullableString(value.sourcePeerId) &&
      isNullableString(value.destinationPeerId) &&
      typeof value.enabled === "boolean"
    );
  }

  if (value.type === "OBSTACLE") {
    return (
      isFiniteNumber(value.x) &&
      isFiniteNumber(value.y) &&
      isFiniteNumber(value.width) &&
      isFiniteNumber(value.height)
    );
  }

  return false;
};

const isValidWorkflowStep = (value: unknown): value is WorkflowStep => {
  if (!isRecord(value)) {
    return false;
  }

  if (
    typeof value.id !== "string" ||
    typeof value.title !== "string" ||
    !ALLOWED_STEP_TYPES.includes(value.type as WorkflowStep["type"]) ||
    !isFiniteNumber(value.tick) ||
    !isNullableString(value.sourcePeerId) ||
    !isNullableString(value.destinationPeerId) ||
    !isNullableString(value.targetEntityId) ||
    !isNullableString(value.movePeerId) ||
    !isFiniteNumber(value.x) ||
    !isFiniteNumber(value.y)
  ) {
    return false;
  }

  if ("refreshPeerId" in value && !isNullableString(value.refreshPeerId)) {
    return false;
  }

  if (
    "refreshProtocol" in value &&
    value.refreshProtocol !== null &&
    !ALLOWED_PROTOCOLS.includes(value.refreshProtocol as PeerRoutingProtocol)
  ) {
    return false;
  }

  if (
    "refreshStartTick" in value &&
    value.refreshStartTick !== null &&
    !isFiniteNumber(value.refreshStartTick)
  ) {
    return false;
  }

  if (
    "refreshInterval" in value &&
    value.refreshInterval !== null &&
    !isFiniteNumber(value.refreshInterval)
  ) {
    return false;
  }

  if ("autoGenerated" in value && typeof value.autoGenerated !== "boolean") {
    return false;
  }

  return true;
};

const parseImportPayload = (raw: string): ImportPayload => {
  let parsed: unknown;

  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Invalid JSON file.");
  }

  if (!isRecord(parsed)) {
    throw new Error("File must contain a JSON object.");
  }

  if (!Array.isArray(parsed.entities) || !parsed.entities.every(isValidNetworkEntity)) {
    throw new Error("Invalid entities list in file.");
  }

  if (!Array.isArray(parsed.steps) || !parsed.steps.every(isValidWorkflowStep)) {
    throw new Error("Invalid steps list in file.");
  }

  return {
    entities: parsed.entities,
    steps: parsed.steps,
  };
};

const getExportFileName = () => {
  const now = new Date();
  const toPart = (value: number) => String(value).padStart(2, "0");
  const stamp = `${now.getFullYear()}${toPart(now.getMonth() + 1)}${toPart(now.getDate())}-${toPart(
    now.getHours(),
  )}${toPart(now.getMinutes())}${toPart(now.getSeconds())}`;
  return `mesh-io-export-${stamp}.json`;
};

export default function WorkspacePage() {
  const { showToast } = useToast();
  const [selectedId, setSelectedId] = useLocalStorage<string | null>("mesh_selected_id", null);
  const [selectedSource, setSelectedSource] = useLocalStorage<"entities" | "steps" | null>(
    "mesh_selected_source",
    null,
  );
  const [isNavCollapsed, setIsNavCollapsed] = useState(false);

  const handleToggleCollapse = () => {
    setIsNavCollapsed((prev) => !prev);
  };
  const [entities, setEntities] = useLocalStorage<NetworkEntity[]>(
    "mesh_entities",
    INITIAL_NETWORK_ENTITIES,
  );
  const [manualSteps, setManualSteps] = useLocalStorage<WorkflowStep[]>(
    "mesh_steps",
    INITIAL_WORKFLOW_STEPS,
  );
  const normalizedManualSteps = useMemo(() => sanitizeManualSteps(manualSteps), [manualSteps]);
  const steps = useMemo(
    () => composeStepsWithRefresh(normalizedManualSteps, entities),
    [normalizedManualSteps, entities],
  );

  useEffect(() => {
    if (normalizedManualSteps.length !== manualSteps.length) {
      setManualSteps(normalizedManualSteps);
    }
  }, [manualSteps.length, normalizedManualSteps, setManualSteps]);

  const setSteps = (nextSteps: WorkflowStep[]) => {
    setManualSteps(sanitizeManualSteps(nextSteps));
  };

  const handleEntitySelect = (id: string) => {
    if (selectedSource === "entities" && selectedId === id) {
      setSelectedId(null);
      setSelectedSource(null);
      return;
    }

    setSelectedId(id);
    setSelectedSource("entities");
  };

  const handleStepSelect = (id: string) => {
    if (selectedSource === "steps" && selectedId === id) {
      setSelectedId(null);
      setSelectedSource(null);
      return;
    }

    setSelectedId(id);
    setSelectedSource("steps");
  };

  const handleClearSelection = () => {
    setSelectedId(null);
    setSelectedSource(null);
  };

  const handleNewWorkspace = () => {
    const hasData = entities.length > 0 || manualSteps.length > 0;

    if (
      hasData &&
      !window.confirm("This action will clear all current entities and steps. Continue?")
    ) {
      return;
    }

    setEntities([]);
    setManualSteps([]);
    handleClearSelection();
    showToast("Started a new simulation");
  };

  const handleExportWorkspace = () => {
    const payload: ImportPayload = {
      entities,
      steps: sanitizeManualSteps(manualSteps),
    };

    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = getExportFileName();
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    showToast("Workspace exported as JSON");
  };

  const handleImportWorkspace = async (file: File) => {
    try {
      const raw = await file.text();
      const payload = parseImportPayload(raw);

      const confirmed = window.confirm(
        "Import action will clear the current environment and replace it with data from the file. Continue?",
      );
      if (!confirmed) {
        return;
      }

      setEntities(payload.entities);
      setManualSteps(sanitizeManualSteps(payload.steps));
      handleClearSelection();
      showToast("Workspace imported successfully");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to import workspace";
      showToast(message);
    }
  };

  useEffect(() => {
    if (selectedSource !== "steps" || !selectedId) {
      return;
    }

    const hasSelectedStep = steps.some((step) => step.id === selectedId);
    if (!hasSelectedStep) {
      setSelectedId(null);
      setSelectedSource(null);
    }
  }, [selectedId, selectedSource, setSelectedId, setSelectedSource, steps]);

  return (
    <div className="workspace-page">
      <div className="workspace-page__nav">
        <Navigation
          selectedId={selectedId}
          selectedSource={selectedSource}
          entities={entities}
          setEntities={setEntities}
          steps={steps}
          setSteps={setSteps}
          onEntitySelect={handleEntitySelect}
          onStepSelect={handleStepSelect}
          onClearSelection={handleClearSelection}
          onFileNew={handleNewWorkspace}
          onFileExport={handleExportWorkspace}
          onFileImport={handleImportWorkspace}
          isCollapsed={isNavCollapsed}
          onToggleCollapse={handleToggleCollapse}
        />
      </div>
      <div className="workspace-page__workspace">
        <Workspace />
      </div>
      <div className="workspace-page__toolbar">
        <Toolbar />
      </div>
      <div className="workspace-page__properties">
        <Properties
          selectedId={selectedId}
          selectedSource={selectedSource}
          entities={entities}
          setEntities={setEntities}
          steps={steps}
          setSteps={setSteps}
          isNavCollapsed={isNavCollapsed}
        />
      </div>
    </div>
  );
}
