import { StepType } from "./enums";
import type { PeerRoutingProtocol } from "./navigation";
import type { UUID } from "./uuid";

export const RefreshAction = {
  BatmanElp: "BATMAN_ELP",
  BatmanOgm: "BATMAN_OGM",
} as const;

export type RefreshAction = (typeof RefreshAction)[keyof typeof RefreshAction];

export type BaseStep = {
  id: UUID;
  title: string;
  tick: number;
};

export type MessageStep = BaseStep & {
  type: typeof StepType.Message;
  sourcePeerId: UUID | null;
  destinationPeerId: UUID | null;
};

export type MoveStep = BaseStep & {
  type: typeof StepType.Move;
  movePeerId: UUID | null;
  x: number;
  y: number;
};

export type ToggleStatusStep = BaseStep & {
  type: typeof StepType.ToggleStatus;
  targetEntityId: UUID | null;
};

export type RefreshStep = BaseStep & {
  type: typeof StepType.Refresh;
  refreshPeerId: UUID;
  refreshProtocol: PeerRoutingProtocol;
  refreshAction?: RefreshAction;
  refreshStartTick: number;
  refreshInterval: number;
  autoGenerated: true;
};

export type ManualWorkflowStep = MessageStep | MoveStep | ToggleStatusStep;

export type WorkflowStep = ManualWorkflowStep | RefreshStep;

export const isMessageStep = (step: WorkflowStep): step is MessageStep => {
  return step.type === StepType.Message;
};

export const isMoveStep = (step: WorkflowStep): step is MoveStep => {
  return step.type === StepType.Move;
};

export const isToggleStatusStep = (step: WorkflowStep): step is ToggleStatusStep => {
  return step.type === StepType.ToggleStatus;
};

export const isRefreshStepType = (step: WorkflowStep): step is RefreshStep => {
  return step.type === StepType.Refresh;
};

export const createStepBase = (base: BaseStep) => {
  return {
    id: base.id,
    title: base.title,
    tick: Math.max(1, Math.floor(base.tick || 1)),
  } satisfies BaseStep;
};

export type WorkflowStepType = WorkflowStep["type"];
