export const DSR_DEFAULT_PACKET_TTL = 50;
export const DSR_DEFAULT_HOP_LIMIT = 32;
export const DSR_ROUTE_CACHE_TIMEOUT = 20;
export const DSR_MAX_REDISCOVERY_ATTEMPTS = 2;
export const DSR_MAX_SALVAGE_COUNT = 1;
