import { peerRoutingProtocols, workflowStepTypes } from "../constants/protocol";
import { EntityType } from "../types/enums";
import type { NetworkEntity, PeerRoutingProtocol } from "../types/navigation";
import type { WorkflowStep } from "../types/workspace/steps";

export type WorkspaceImportPayload = {
  entities: NetworkEntity[];
  steps: WorkflowStep[];
};

const isRecord = (value: unknown): value is Record<string, unknown> => {
  return typeof value === "object" && value !== null;
};

const isFiniteNumber = (value: unknown): value is number => {
  return typeof value === "number" && Number.isFinite(value);
};

const isNullableString = (value: unknown): value is string | null => {
  return typeof value === "string" || value === null;
};

const isValidProtocolList = (value: unknown): value is PeerRoutingProtocol[] => {
  return (
    Array.isArray(value) &&
    value.every((item) => peerRoutingProtocols.includes(item as PeerRoutingProtocol))
  );
};

const isValidNetworkEntity = (value: unknown): value is NetworkEntity => {
  if (!isRecord(value) || typeof value.id !== "string" || typeof value.name !== "string") {
    return false;
  }

  if ("locked" in value && typeof value.locked !== "boolean") {
    return false;
  }

  if (value.type === EntityType.Peer) {
    return (
      isFiniteNumber(value.x) &&
      isFiniteNumber(value.y) &&
      isFiniteNumber(value.range) &&
      value.range > 0 &&
      typeof value.enabled === "boolean" &&
      isValidProtocolList(value.protocols) &&
      isFiniteNumber(value.batmanOgmInterval) &&
      isFiniteNumber(value.batmanPurgeTimeout)
    );
  }

  if (value.type === EntityType.Link) {
    return (
      isNullableString(value.sourcePeerId) &&
      isNullableString(value.destinationPeerId) &&
      typeof value.enabled === "boolean"
    );
  }

  if (value.type === EntityType.Obstacle) {
    return (
      isFiniteNumber(value.x) &&
      isFiniteNumber(value.y) &&
      isFiniteNumber(value.width) &&
      value.width > 0 &&
      isFiniteNumber(value.height) &&
      value.height > 0
    );
  }

  return false;
};

const isValidWorkflowStep = (value: unknown): value is WorkflowStep => {
  if (!isRecord(value)) {
    return false;
  }

  if (
    typeof value.id !== "string" ||
    typeof value.title !== "string" ||
    !workflowStepTypes.includes(value.type as WorkflowStep["type"]) ||
    !isFiniteNumber(value.tick) ||
    !isNullableString(value.sourcePeerId) ||
    !isNullableString(value.destinationPeerId) ||
    !isNullableString(value.targetEntityId) ||
    !isNullableString(value.movePeerId) ||
    !isFiniteNumber(value.x) ||
    !isFiniteNumber(value.y)
  ) {
    return false;
  }

  if ("refreshPeerId" in value && !isNullableString(value.refreshPeerId)) {
    return false;
  }

  if (
    "refreshProtocol" in value &&
    value.refreshProtocol !== null &&
    !peerRoutingProtocols.includes(value.refreshProtocol as PeerRoutingProtocol)
  ) {
    return false;
  }

  if (
    "refreshStartTick" in value &&
    value.refreshStartTick !== null &&
    !isFiniteNumber(value.refreshStartTick)
  ) {
    return false;
  }

  if (
    "refreshInterval" in value &&
    value.refreshInterval !== null &&
    !isFiniteNumber(value.refreshInterval)
  ) {
    return false;
  }

  if ("autoGenerated" in value && typeof value.autoGenerated !== "boolean") {
    return false;
  }

  return true;
};

export const parseWorkspaceImportPayload = (raw: string): WorkspaceImportPayload => {
  let parsed: unknown;

  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Invalid JSON file.");
  }

  if (!isRecord(parsed)) {
    throw new Error("File must contain a JSON object.");
  }

  if (!Array.isArray(parsed.entities) || !parsed.entities.every(isValidNetworkEntity)) {
    throw new Error("Invalid entities list in file.");
  }

  if (!Array.isArray(parsed.steps) || !parsed.steps.every(isValidWorkflowStep)) {
    throw new Error("Invalid steps list in file.");
  }

  return {
    entities: parsed.entities,
    steps: parsed.steps,
  };
};

export const getWorkspaceExportFileName = (date = new Date()) => {
  const toPart = (value: number) => String(value).padStart(2, "0");
  const stamp = `${date.getFullYear()}${toPart(date.getMonth() + 1)}${toPart(date.getDate())}-${toPart(
    date.getHours(),
  )}${toPart(date.getMinutes())}${toPart(date.getSeconds())}`;
  return `mesh-io-export-${stamp}.json`;
};
