import { EntityType, RoutingProtocol, StepType } from "../../types/enums";
import type { NetworkEntity, PeerEntity } from "../../types/navigation";
import type { WorkflowStep } from "../../types/steps";

export const isRefreshStep = (step: WorkflowStep) => step.type === StepType.Refresh;

const sortStepsByTick = (steps: WorkflowStep[]) => {
  return [...steps].sort((a, b) => {
    if (a.tick !== b.tick) {
      return a.tick - b.tick;
    }
    return 0;
  });
};

const buildBatmanRefreshTicks = (
  manualSteps: WorkflowStep[],
  peer: PeerEntity,
  maxTick: number,
) => {
  const interval = Math.max(1, Math.floor(peer.batmanOgmInterval));
  const toggleParityByTick = new Map<number, number>();

  for (const step of manualSteps) {
    if (step.type !== StepType.ToggleStatus || step.targetEntityId !== peer.id) {
      continue;
    }
    toggleParityByTick.set(step.tick, (toggleParityByTick.get(step.tick) ?? 0) + 1);
  }

  let isEnabled = peer.enabled;
  let activeStartTick: number | null = isEnabled ? 0 : null;
  const refreshTicks: Array<{ tick: number; startTick: number }> = [];

  for (let tick = 0; tick <= maxTick; tick += 1) {
    const toggleCount = toggleParityByTick.get(tick) ?? 0;
    const nextEnabled = toggleCount % 2 === 0 ? isEnabled : !isEnabled;

    if (!isEnabled && nextEnabled) {
      activeStartTick = tick;
    }

    if (nextEnabled && activeStartTick !== null && (tick - activeStartTick) % interval === 0) {
      refreshTicks.push({ tick, startTick: activeStartTick });
    }

    if (isEnabled && !nextEnabled) {
      activeStartTick = null;
    }

    isEnabled = nextEnabled;
  }

  return refreshTicks;
};

const buildRefreshStepsForPeer = (
  manualSteps: WorkflowStep[],
  peer: PeerEntity,
  maxTick: number,
) => {
  if (!peer.protocols.includes(RoutingProtocol.BATMAN)) {
    return [];
  }

  const interval = Math.max(1, Math.floor(peer.batmanOgmInterval));
  return buildBatmanRefreshTicks(manualSteps, peer, maxTick).map(({ tick, startTick }) => ({
    id: `refresh-batman-${peer.id}-${tick}`,
    title: `BATMAN Refresh on ${peer.name}`,
    type: StepType.Refresh,
    tick,
    sourcePeerId: null,
    destinationPeerId: null,
    targetEntityId: null,
    movePeerId: null,
    x: 0,
    y: 0,
    refreshPeerId: peer.id,
    refreshProtocol: RoutingProtocol.BATMAN,
    refreshStartTick: startTick,
    refreshInterval: interval,
    autoGenerated: true,
  }));
};

const normalizeManualStep = (step: WorkflowStep, index: number): WorkflowStep => {
  const safeTick = Number.isFinite(step.tick) && step.tick > 0 ? Math.floor(step.tick) : index + 1;
  const safeType = step.type === StepType.Refresh ? StepType.Move : step.type;

  return {
    ...step,
    type: safeType,
    tick: safeTick,
    sourcePeerId: typeof step.sourcePeerId === "string" ? step.sourcePeerId : null,
    destinationPeerId: typeof step.destinationPeerId === "string" ? step.destinationPeerId : null,
    targetEntityId: typeof step.targetEntityId === "string" ? step.targetEntityId : null,
    movePeerId: typeof step.movePeerId === "string" ? step.movePeerId : null,
    x: typeof step.x === "number" ? step.x : 0,
    y: typeof step.y === "number" ? step.y : 0,
    refreshPeerId: null,
    refreshProtocol: null,
    refreshStartTick: null,
    refreshInterval: null,
    autoGenerated: false,
  };
};

export const sanitizeManualSteps = (steps: WorkflowStep[]) => {
  return steps.filter((step) => !isRefreshStep(step)).map(normalizeManualStep);
};

export const composeStepsWithRefresh = (steps: WorkflowStep[], entities: NetworkEntity[]) => {
  const manualSteps = sanitizeManualSteps(sortStepsByTick(steps));
  const peers = entities.filter((entity): entity is PeerEntity => entity.type === EntityType.Peer);
  const maxTick = Math.max(1, ...manualSteps.map((step) => step.tick));

  const refreshByTick = new Map<number, WorkflowStep[]>();
  for (const peer of peers) {
    const refreshSteps = buildRefreshStepsForPeer(manualSteps, peer, maxTick);
    for (const refreshStep of refreshSteps) {
      const bucket = refreshByTick.get(refreshStep.tick) ?? [];
      bucket.push(refreshStep);
      refreshByTick.set(refreshStep.tick, bucket);
    }
  }

  for (const [tick, bucket] of refreshByTick.entries()) {
    bucket.sort((a, b) => a.title.localeCompare(b.title));
    refreshByTick.set(tick, bucket);
  }

  const result: WorkflowStep[] = [];
  const stepsByTick = new Map<number, WorkflowStep[]>();
  for (const step of manualSteps) {
    const bucket = stepsByTick.get(step.tick) ?? [];
    bucket.push(step);
    stepsByTick.set(step.tick, bucket);
  }

  for (let tick = 0; tick <= maxTick; tick += 1) {
    const manualAtTick = stepsByTick.get(tick) ?? [];
    result.push(...manualAtTick);
    result.push(...(refreshByTick.get(tick) ?? []));
  }

  return result;
};
