import { EntityType, RoutingProtocol, StepType } from "../../types/enums";
import type { NetworkEntity, PeerEntity } from "../../types/navigation";
import {
  createStepBase,
  isMessageStep,
  isMoveStep,
  isRefreshStepType,
  isToggleStatusStep,
  type ManualWorkflowStep,
  type MessageStep,
  type MoveStep,
  type RefreshStep,
  type ToggleStatusStep,
  type WorkflowStep,
} from "../../types/workspace/steps";

export const isRefreshStep = (step: WorkflowStep): step is RefreshStep => isRefreshStepType(step);

const sortStepsByTick = (steps: WorkflowStep[]) => {
  return [...steps].sort((a, b) => {
    if (a.tick !== b.tick) {
      return a.tick - b.tick;
    }
    return 0;
  });
};

const buildBatmanRefreshTicks = (
  manualSteps: WorkflowStep[],
  peer: PeerEntity,
  maxTick: number,
) => {
  const interval = Math.max(1, Math.floor(peer.batmanOgmInterval));
  const toggleParityByTick = new Map<number, number>();

  for (const step of manualSteps) {
    if (step.type !== StepType.ToggleStatus || step.targetEntityId !== peer.id) {
      continue;
    }
    toggleParityByTick.set(step.tick, (toggleParityByTick.get(step.tick) ?? 0) + 1);
  }

  let isEnabled = peer.enabled;
  let activeStartTick: number | null = isEnabled ? 0 : null;
  const refreshTicks: Array<{ tick: number; startTick: number }> = [];

  for (let tick = 0; tick <= maxTick; tick += 1) {
    const toggleCount = toggleParityByTick.get(tick) ?? 0;
    const nextEnabled = toggleCount % 2 === 0 ? isEnabled : !isEnabled;

    if (!isEnabled && nextEnabled) {
      activeStartTick = tick;
    }

    if (nextEnabled && activeStartTick !== null && (tick - activeStartTick) % interval === 0) {
      refreshTicks.push({ tick, startTick: activeStartTick });
    }

    if (isEnabled && !nextEnabled) {
      activeStartTick = null;
    }

    isEnabled = nextEnabled;
  }

  return refreshTicks;
};

const buildRefreshStepsForPeer = (
  manualSteps: ManualWorkflowStep[],
  peer: PeerEntity,
  maxTick: number,
): RefreshStep[] => {
  if (!peer.protocols.includes(RoutingProtocol.BATMAN)) {
    return [];
  }

  const interval = Math.max(1, Math.floor(peer.batmanOgmInterval));
  return buildBatmanRefreshTicks(manualSteps, peer, maxTick).map(({ tick, startTick }) => ({
    ...createStepBase({
      id: `refresh-batman-${peer.id}-${tick}`,
      title: `BATMAN Refresh on ${peer.name}`,
      tick,
    }),
    type: StepType.Refresh,
    refreshPeerId: peer.id,
    refreshProtocol: RoutingProtocol.BATMAN,
    refreshStartTick: startTick,
    refreshInterval: interval,
    autoGenerated: true,
  }));
};

const normalizeMessageStep = (step: MessageStep, index: number): MessageStep => {
  const base = createStepBase({
    ...step,
    tick: Number.isFinite(step.tick) ? step.tick : index + 1,
  });
  return {
    ...base,
    type: StepType.Message,
    sourcePeerId: step.sourcePeerId,
    destinationPeerId: step.destinationPeerId,
  };
};

const normalizeMoveStep = (step: MoveStep, index: number): MoveStep => {
  const base = createStepBase({
    ...step,
    tick: Number.isFinite(step.tick) ? step.tick : index + 1,
  });
  return {
    ...base,
    type: StepType.Move,
    movePeerId: step.movePeerId,
    x: Number.isFinite(step.x) ? step.x : 0,
    y: Number.isFinite(step.y) ? step.y : 0,
  };
};

const normalizeToggleStep = (step: ToggleStatusStep, index: number): ToggleStatusStep => {
  const base = createStepBase({
    ...step,
    tick: Number.isFinite(step.tick) ? step.tick : index + 1,
  });
  return {
    ...base,
    type: StepType.ToggleStatus,
    targetEntityId: step.targetEntityId,
  };
};

const normalizeManualStep = (step: WorkflowStep, index: number): ManualWorkflowStep | null => {
  if (isRefreshStep(step)) {
    return null;
  }

  if (isMessageStep(step)) {
    if (
      !step.sourcePeerId ||
      !step.destinationPeerId ||
      step.sourcePeerId === step.destinationPeerId
    ) {
      return null;
    }
    return normalizeMessageStep(step, index);
  }

  if (isMoveStep(step)) {
    if (!step.movePeerId) {
      return null;
    }
    return normalizeMoveStep(step, index);
  }

  if (isToggleStatusStep(step)) {
    if (!step.targetEntityId) {
      return null;
    }
    return normalizeToggleStep(step, index);
  }

  return null;
};

export const sanitizeManualSteps = (steps: WorkflowStep[]) => {
  return steps
    .map((step, index) => normalizeManualStep(step, index))
    .filter((step): step is ManualWorkflowStep => step !== null);
};

export const composeStepsWithRefresh = (steps: WorkflowStep[], entities: NetworkEntity[]) => {
  const manualSteps = sanitizeManualSteps(sortStepsByTick(steps));
  const peers = entities.filter((entity): entity is PeerEntity => entity.type === EntityType.Peer);
  const maxTick = Math.max(1, ...manualSteps.map((step) => step.tick));

  const refreshByTick = new Map<number, WorkflowStep[]>();
  for (const peer of peers) {
    const refreshSteps = buildRefreshStepsForPeer(manualSteps, peer, maxTick);
    for (const refreshStep of refreshSteps) {
      const bucket = refreshByTick.get(refreshStep.tick) ?? [];
      bucket.push(refreshStep);
      refreshByTick.set(refreshStep.tick, bucket);
    }
  }

  for (const [tick, bucket] of refreshByTick.entries()) {
    bucket.sort((a, b) => a.title.localeCompare(b.title));
    refreshByTick.set(tick, bucket);
  }

  const result: WorkflowStep[] = [];
  const stepsByTick = new Map<number, WorkflowStep[]>();
  for (const step of manualSteps) {
    const bucket = stepsByTick.get(step.tick) ?? [];
    bucket.push(step);
    stepsByTick.set(step.tick, bucket);
  }

  for (let tick = 0; tick <= maxTick; tick += 1) {
    const manualAtTick = stepsByTick.get(tick) ?? [];
    result.push(...manualAtTick);
    result.push(...(refreshByTick.get(tick) ?? []));
  }

  return result;
};
