import type { WorkflowStep } from "../../types/steps";

export const INITIAL_WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: "step-1",
    title: "Select Devices",
    type: "MOVE",
    tick: 1,
    sourcePeerId: null,
    destinationPeerId: null,
    targetEntityId: null,
    movePeerId: null,
    x: 0,
    y: 0,
  },
  {
    id: "step-2",
    title: "Configure Links",
    type: "MESSAGE",
    tick: 2,
    sourcePeerId: null,
    destinationPeerId: null,
    targetEntityId: null,
    movePeerId: null,
    x: 0,
    y: 0,
  },
  {
    id: "step-3",
    title: "Validate Topology",
    type: "TOGGLE",
    tick: 3,
    sourcePeerId: null,
    destinationPeerId: null,
    targetEntityId: null,
    movePeerId: null,
    x: 0,
    y: 0,
  },
];
