import { RoutingProtocol } from "./protocols";
import { StepType } from "./steptype";
import type { UUID } from "./uuid";

export const BatmanRefreshAction = {
  Elp: "BATMAN_ELP",
  Ogm: "BATMAN_OGM",
} as const;

export type BatmanRefreshAction = (typeof BatmanRefreshAction)[keyof typeof BatmanRefreshAction];

export const OlsrRefreshAction = {
  Hello: "OLSR_HELLO",
  Tc: "OLSR_TC",
} as const;

export type OlsrRefreshAction = (typeof OlsrRefreshAction)[keyof typeof OlsrRefreshAction];

export const DsdvRefreshAction = {
  FullDump: "DSDV_FULL_DUMP",
  Incremental: "DSDV_INCREMENTAL",
} as const;

export type DsdvRefreshAction = (typeof DsdvRefreshAction)[keyof typeof DsdvRefreshAction];

export const AodvRefreshAction = {
  Hello: "AODV_HELLO",
} as const;

export type AodvRefreshAction = (typeof AodvRefreshAction)[keyof typeof AodvRefreshAction];

export const RefreshAction = {
  BatmanElp: BatmanRefreshAction.Elp,
  BatmanOgm: BatmanRefreshAction.Ogm,
  DsdvFullDump: DsdvRefreshAction.FullDump,
  DsdvIncremental: DsdvRefreshAction.Incremental,
  AodvHello: AodvRefreshAction.Hello,
  OlsrHello: OlsrRefreshAction.Hello,
  OlsrTc: OlsrRefreshAction.Tc,
} as const;

export type RefreshAction = (typeof RefreshAction)[keyof typeof RefreshAction];

export interface BaseStep {
  id: UUID;
  title: string;
  tick: number;
}

export interface MessageStep extends BaseStep {
  type: typeof StepType.Message;
  sourcePeerId: UUID | null;
  destinationPeerId: UUID | null;
}

export interface MoveStep extends BaseStep {
  type: typeof StepType.Move;
  movePeerId: UUID | null;
  x: number;
  y: number;
}

export interface ToggleStep extends BaseStep {
  type: typeof StepType.Toggle;
  targetEntityId: UUID | null;
}

export interface BaseRefreshStep extends BaseStep {
  type: typeof StepType.Refresh;
  refreshPeerId: UUID;
  refreshProtocol: RoutingProtocol;
  refreshStartTick: number;
  refreshInterval: number;
  autoGenerated: true;
}

export interface BatmanRefreshStep extends BaseRefreshStep {
  refreshProtocol: typeof RoutingProtocol.BATMAN;
  refreshAction?: BatmanRefreshAction;
}

export interface OlsrRefreshStep extends BaseRefreshStep {
  refreshProtocol: typeof RoutingProtocol.OLSR;
  refreshAction?: OlsrRefreshAction;
}

export interface DsdvRefreshStep extends BaseRefreshStep {
  refreshProtocol: typeof RoutingProtocol.DSDV;
  refreshAction?: DsdvRefreshAction;
}

export interface AodvRefreshStep extends BaseRefreshStep {
  refreshProtocol: typeof RoutingProtocol.AODV;
  refreshAction?: AodvRefreshAction;
}

export type RefreshStep = BatmanRefreshStep | OlsrRefreshStep | DsdvRefreshStep | AodvRefreshStep;

export type ToggleStatusStep = ToggleStep;

export type ManualWorkflowStep = MessageStep | MoveStep | ToggleStep;

export type WorkflowStep = ManualWorkflowStep | RefreshStep;

export const isMessageStep = (step: WorkflowStep): step is MessageStep => {
  return step.type === StepType.Message;
};

export const isMoveStep = (step: WorkflowStep): step is MoveStep => {
  return step.type === StepType.Move;
};

export const isToggleStep = (step: WorkflowStep): step is ToggleStep => {
  return step.type === StepType.Toggle;
};

export const isToggleStatusStep = (step: WorkflowStep): step is ToggleStep => {
  return isToggleStep(step);
};

export const isRefreshStepType = (step: WorkflowStep): step is RefreshStep => {
  return step.type === StepType.Refresh;
};

export const createStepBase = (base: BaseStep) => {
  return {
    id: base.id,
    title: base.title,
    tick: Math.max(1, Math.floor(base.tick || 1)),
  } satisfies BaseStep;
};

export type WorkflowStepType = WorkflowStep["type"];
